# Configuration file alacritty under ~/.config/alacritty/alacritty.toml
# https://alacritty.org/config-alacritty.html

[window]
decorations = "Buttonless"

[font]
size = 16

[font.offset]
x = 0
y = 2

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
